In [1]:
import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.svm import SVR
from sklearn.metrics import mean_squared_error

In [2]:
# Load the dataset
tweets_d = pd.read_csv('Data/tweets_disc_cleaned.csv')
tweets_c = pd.read_csv('Data/tweets_ctrl_cleaned.csv')
data = pd.concat([tweets_d])
data

,date,id,content,likes,retweets,disc_cat,Unnamed: 0.1,disc_cat_num
0,28 February 2023,1630587451436683264,bitch lmfaooooo gone rock sock ass,0,0,gender,NaN,2
1,28 February 2023,1630587450710958081,nvr vw person simpli cost repair hassl get don...,0,0,gender,NaN,2
2,28 February 2023,1630587450673319940,hate wen bitch say stop act care df said act l...,0,0,gender,NaN,2
3,28 February 2023,1630587450547634179,dnc pay well ask brooklyn dad hes lucki get pe...,0,0,gender,NaN,2
4,28 February 2023,1630587449503264769,sinong bitch ba yung hindi marunong mag sorri ...,0,0,gender,NaN,2
...,...,...,...,...,...,...,...,...
210913,28 February 2023,1630401406883561472,NaN,3,0,mental_health,105706.0,4
210914,28 February 2023,1630401254798118913,make sens,1,0,mental_health,105707.0,4
210915,28 February 2023,1630401175995527169,mean make sens miz host,0,0,mental_health,105708.0,4
210916,28 February 2023,1630400994222948352,disrespect key lime pieoh use lubric,1,0,mental_health,105709.0,4
210917,28 February 2023,1630400083152994304,compartment nois block itkeep,0,0,mental_health,105710.0,4

In [5]:
# Remove rows with NaN values
data = data.dropna()

In [6]:
# Create a TF-IDF representation of the tweets
vectorizer = TfidfVectorizer(stop_words='english')
X = vectorizer.fit_transform(data['content'])

In [ ]:
# Add features for the presence of each discriminatory word
discriminatory_words = ['word1', 'word2', 'word3', ...]
for word in discriminatory_words:
    X = pd.concat([X, data['tweet'].str.contains(word)], axis=1)

In [ ]:
# Use the number of discriminatory words as the label
y = data['num_discriminatory_words']

In [ ]:
# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [ ]:
# Train an SVR model
model = SVR(kernel='linear', C=1)
model.fit(X_train, y_train)

In [ ]:
# Evaluate the model
y_pred = model.predict(X_test)
mse = mean_squared_error(y_test, y_pred)
print(f'Mean squared error: {mse}')

In [ ]:
# Provide suggestions based on the number of discriminatory words
if y_pred < 2:
    print('This tweet contains no discriminatory language.')
elif y_pred < 5:
    print('Consider revising this tweet to remove any potentially discriminatory language.')
else:
    print('This tweet contains a high number of discriminatory words and should be reviewed carefully.')